# PostgreSQL. Versions 8.2 and up are supported.

development:
  adapter: sqlite3
  database: db/journal_development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: journal_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: journal_production
  pool: 5
  username: postgres
  password:
