# PostgreSQL. Versions 8.2 and up are supported.

development:
  adapter: postgresql
  encoding: unicode
  database: journal_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: journal_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: journal_production
  pool: 5
  username: postgres
  password:
